### ISSUE TITLE
No progress in model training for large number of columns

### ISSUE THREAD

**Issue by vinay-k12** [worldbank/REaLTabFormer#17]
I'm trying to train the model on transactional data that has around 78 columns with numerical, text and categorical columns. I am trying to modify the training size by modifying rows and columns, but still, training is not progressing at all.

**Comment by vinay-k12** [comment]
Here is the error: 

<img width="1102" alt="image" src="https://github.com/avsolatorio/REaLTabFormer/assets/19322429/a9ac7f20-b7c4-473e-b7df-329776fdc7ba">

**Comment by virajpwr** [comment]
I get the same error. It has to do with the dependency from transformers. Where you able to resolve the issue?

**Comment by avsolatorio** [comment]
@vinay-k12 @virajpwr, closing this as release [v0.1.3](https://github.com/worldbank/REaLTabFormer/releases/tag/v0.1.3) should solve this issue.
