### ISSUE TITLE
New PyPi release

### ISSUE THREAD

**Issue by echatzikyriakidis** [worldbank/REaLTabFormer#18]
Hi @avsolatorio,

I was wondering if you can create a new version in PyPi for the library.

Specifically, what I want is the following fix which is in main branch but is missing from the latest version (0.1.1):

https://github.com/worldbank/REaLTabFormer/commit/bf1a38ef8f202372956ac57a363289c505967982

Is it possible to have this? Thanks!

**Comment by avsolatorio** [comment]
Hey, @echatzikyriakidis v0.1.2 is now available on PyPi. 😀

**Comment by echatzikyriakidis** [comment]
Thank you @avsolatorio !!!
