### ISSUE TITLE
AssertionError: The target length 10 of the data doesn't include the numeric precision at 20. Increase max_len to at least 22.

### ISSUE THREAD

**Issue by vinay-k12** [worldbank/REaLTabFormer#30]
<img width="1021" alt="image" src="https://github.com/worldbank/REaLTabFormer/assets/19322429/a2f696c3-d86a-40d5-9cf9-4fa2a370237a">

How to resolve this?

**Comment by avsolatorio** [comment]
@vinay-k12 , I am closing this as inactive. Kindly reopen if my suggestion above does not work, or if you are still facing issues. Thanks!
