### ISSUE TITLE
_validate_get_device() could be nice to be called also in model.sample() and model.predict()

### ISSUE THREAD

**Issue by echatzikyriakidis** [worldbank/REaLTabFormer#32]
Hi!

I have noticed that _validate_get_device() is called only on model.fit() but it could be nice if is called also in model.sample() and model.predict() so that there is no need to pass device argument in the methods when no cuda is available to use CPU. model.fit() already calls it and there is no need to pass device, it automatically detects what to use.

**Comment by avsolatorio** [comment]
@echatzikyriakidis, thanks for noting this! I pushed a patch to use `_validate_get_device` in the other interfaces. 😀

**Comment by echatzikyriakidis** [comment]
Thank you!
