### ISSUE TITLE
Conditional generation? 

### ISSUE THREAD

**Issue by gminorcoles** [worldbank/REaLTabFormer#48]
Hi I found your work today I think from googling about overfitting and data copying in these kinds of models. There are some very interesting ideas re: DCR and the Q metric that I think are pretty interesting.  I have a need to generate data conditionally. I have some labels for medical imaging data and I need to sample using the timestamp and a label as the conditional information. 

Could I add the conditional data to the text of the input? Is this a use case which anyone has explored? 

thanks

**Comment by Contributorrandom** [comment]
This is an interesting use case ? Did you get any thread ?

**Comment by Contributorrandom** [comment]
Okay, cool. I was thinking of a different use case .

**Comment by avsolatorio** [comment]
> Hi I found your work today I think from googling about overfitting and data copying in these kinds of models. There are some very interesting ideas re: DCR and the Q metric that I think are pretty interesting. I have a need to generate data conditionally. I have some labels for medical imaging data and I need to sample using the timestamp and a label as the conditional information.
> 
> Could I add the conditional data to the text of the input? Is this a use case which anyone has explored?
> 
> thanks

Hello @gminorcoles , thanks for looking into this project! Conditional generation is possible provided that your conditioning variables are located at the first columns of your table.

There is a `seed_input` argument that can then be used to conditionally sample given the values for the first N columns that is provided.

See: https://github.com/worldbank/REaLTabFormer/blob/4f3fa54a52085985b6e03e29dd71850b2a9ba324/src/realtabformer/realtabformer.py#L1159C4-L1159C4

Indeed, the code is a bit convoluted currently. I need to find more time to refactor this and make things simpler! 😅

But any contributions are welcome! And let me know if you have any questions. 😊
