### ISSUE TITLE
Documentation page not working

### ISSUE THREAD

**Issue by sfragkoul** [worldbank/REaLTabFormer#68]
Hey there,

thanks for developing and maintaining this package.

I was trying to skim through the [Documentation](https://avsolatorio.github.io/REaLTabFormer/) but it yields a _404-File not found_ error.

Looking forward to implement REaLTabFormer!

Thanks for your time,
Stella

**Comment by avsolatorio** [comment]
Hello @sfragkoul , the documentation is hosted here: https://worldbank.github.io/REaLTabFormer/ 😀

**Comment by sfragkoul** [comment]
Thanks!

**Comment by sfragkoul** [comment]
Thanks!
