### ISSUE TITLE
Newest transformers v4.46.0 crashes .fit() [BREAKING Change]

### ISSUE THREAD

**Issue by N1h1l1sT** [worldbank/REaLTabFormer#90]
Current REaLTabFormer version has a requirement for transformers version `>=4.41.0`.
However, the newest version of transformers (v4.46.0) seems to have breaking changes that make REaLTabFormer crash.

On `https://github.com/worldbank/REaLTabFormer/blob/main/src/realtabformer/rtf_trainer.py#L83` the `__init__` function of `transformers .Trainer` is called, and it takes the arguments in a different order, which makes the argument `optimizers` to take a value of `None` instead of `(None, None)`, so when later on it tries to extract 2 variables from it, it crashes.

It works great with transformers version 4.41.2, hence the breaking change was done in a future version (but I'm unsure exactly when).

**Comment by avsolatorio** [comment]
Fixed in: https://github.com/worldbank/REaLTabFormer/pull/91
