### ISSUE TITLE
Issues Running REaLTabFormer_GeoValidator_Example.ipynb on Google Colab

### ISSUE THREAD

**Issue by ArshiaIlaty** [worldbank/REaLTabFormer#92]
Hello,

Hope you are doing well. I encountered a couple of issues while trying to run the REaLTabFormer_GeoValidator_Example.ipynb notebook on Google Colab:

1. `evaluation_strategy` is deprecated and will be removed in version 4.46 of Transformers. Use `eval_strategy` instead
2. TypeError: cannot unpack non-iterable NoneType object

Both issues occurred when the model started to fit.

Could you please assist in resolving these issues or guide me on the correct setup to run the notebook successfully?

**Comment by avsolatorio** [comment]
Hello @ArshiaIlaty, thank you for reporting this! I have published the updated package (v0.2.2) containing the fix from this PR https://github.com/worldbank/REaLTabFormer/pull/91 . This should be working now. Please try again. :)

**Comment by ArshiaIlaty** [comment]
Hi @avsolatorio I truly appreciate it.
