### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by adgirban** [worldbank/REaLTabFormer#93]
rtf_model = REaLTabFormer(
    model_type="tabular",
    gradient_accumulation_steps=4,
    logging_steps=100)

rtf_model.fit(train)

I get the following error when running the above:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[25], line 17
      9 rtf_model = REaLTabFormer(
     10     model_type="tabular",
     11     gradient_accumulation_steps=4,
     12     logging_steps=100)
     14 # # Fit the model on the dataset.
     15 # # Additional parameters can be
     16 # # passed to the `.fit` method.
---> 17 rtf_model.fit(train)
     19 # # Save the model to the current directory.
     20 # # A new directory `rtf_model/` will be created.
     21 # # In it, a directory with the model's
     22 # # experiment id `idXXXX` will also be created
     23 # # where the artefacts of the model will be stored.
     24 rtf_model.save("rtf_model/")

File /opt/conda/lib/python3.10/site-packages/realtabformer/realtabformer.py:458, in REaLTabFormer.fit(self, df, in_df, join_on, resume_from_checkpoint, device, num_bootstrap, frac, frac_max_data, qt_max, qt_max_default, qt_interval, qt_interval_unique, distance, quantile, n_critic, n_critic_stop, gen_rounds, sensitivity_max_col_nums, use_ks, full_sensitivity, sensitivity_orig_frac_multiple, orig_samples_rounds, load_from_best_mean_sensitivity, target_col)
    456         trainer.train(resume_from_checkpoint=resume_from_checkpoint)
    457     else:
--> 458         trainer = self._train_with_sensitivity(
    459             df,
    460             device,
    461             num_bootstrap=num_bootstrap,
    462             frac=frac,
    463             frac_max_data=frac_max_data,
    464             qt_max=qt_max,
    465             qt_max_default=qt_max_default,
    466             qt_interval=qt_interval,
    467             qt_interval_unique=qt_interval_unique,
    468             distance=distance,
    469             quantile=quantile,
    470             n_critic=n_critic,
    471             n_critic_stop=n_critic_stop,
    472             gen_rounds=gen_rounds,
    473             resume_from_checkpoint=resume_from_checkpoint,
    474             sensitivity_max_col_nums=sensitivity_max_col_nums,
    475             use_ks=use_ks,
    476             full_sensitivity=full_sensitivity,
    477             sensitivity_orig_frac_multiple=sensitivity_orig_frac_multiple,
    478             orig_samples_rounds=orig_samples_rounds,
    479             load_from_best_mean_sensitivity=load_from_best_mean_sensitivity,
    480         )
    482     del self.dataset
    484 elif self.model_type == ModelType.relational:

File /opt/conda/lib/python3.10/site-packages/realtabformer/realtabformer.py:697, in REaLTabFormer._train_with_sensitivity(self, df, device, num_bootstrap, frac, frac_max_data, qt_max, qt_max_default, qt_interval, qt_interval_unique, distance, quantile, n_critic, n_critic_stop, gen_rounds, sensitivity_max_col_nums, use_ks, resume_from_checkpoint, full_sensitivity, sensitivity_orig_frac_multiple, orig_samples_rounds, load_from_best_mean_sensitivity)
    695 # Perform the discriminator sampling every `n_critic` epochs
    696 if trainer is None:
--> 697     trainer = self._fit_tabular(
    698         df,
    699         device=device,
    700         num_train_epochs=num_train_epochs,
    701         target_epochs=self.epochs,
    702     )
    703     trainer.train(resume_from_checkpoint=False)
    704 else:

File /opt/conda/lib/python3.10/site-packages/realtabformer/realtabformer.py:1094, in REaLTabFormer._fit_tabular(self, df, device, num_train_epochs, target_epochs)
   1091 if device == torch.device("cuda"):
   1092     self.model.cuda()
-> 1094 return self._build_tabular_trainer(
   1095     device=device,
   1096     num_train_epochs=num_train_epochs,
   1097     target_epochs=target_epochs,
   1098 )

File /opt/conda/lib/python3.10/site-packages/realtabformer/realtabformer.py:1140, in REaLTabFormer._build_tabular_trainer(self, device, num_train_epochs, target_epochs)
   1133     callbacks = [
   1134         EarlyStoppingCallback(
   1135             self.early_stopping_patience, self.early_stopping_threshold
   1136         )
   1137     ]
   1139 assert self.dataset
-> 1140 trainer = ResumableTrainer(
   1141     target_epochs=target_epochs,
   1142     save_epochs=None,
   1143     model=self.model,
   1144     args=TrainingArguments(**training_args_kwargs),
   1145     data_collator=None,  # Use the default_data_collator
   1146     callbacks=callbacks,
   1147     **self.dataset,
   1148 )
   1150 return trainer

File /opt/conda/lib/python3.10/site-packages/realtabformer/rtf_trainer.py:83, in ResumableTrainer.__init__(self, target_epochs, save_epochs, model, args, data_collator, train_dataset, eval_dataset, tokenizer, model_init, compute_metrics, callbacks, optimizers, preprocess_logits_for_metrics)
     79     callbacks = []
     81 callbacks.append(SaveEpochEndCallback(save_epochs=save_epochs))
---> 83 super().__init__(
     84     model,
     85     args,
     86     data_collator,
     87     train_dataset,
     88     eval_dataset,
     89     tokenizer,
     90     model_init,
     91     compute_metrics,
     92     callbacks,
     93     optimizers,
     94     preprocess_logits_for_metrics,
     95 )
     96 self.target_epochs = target_epochs

File /opt/conda/lib/python3.10/site-packages/transformers/utils/deprecation.py:165, in deprecate_kwarg.<locals>.wrapper.<locals>.wrapped_func(*args, **kwargs)
    161 elif minimum_action in (Action.NOTIFY, Action.NOTIFY_ALWAYS):
    162     # DeprecationWarning is ignored by default, so we use FutureWarning instead
    163     warnings.warn(message, FutureWarning, stacklevel=2)
--> 165 return func(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:600, in Trainer.__init__(self, model, args, data_collator, train_dataset, eval_dataset, processing_class, model_init, compute_loss_func, compute_metrics, callbacks, optimizers, preprocess_logits_for_metrics)
    598 self.compute_metrics = compute_metrics
    599 self.preprocess_logits_for_metrics = preprocess_logits_for_metrics
--> 600 self.optimizer, self.lr_scheduler = optimizers
    601 if model_init is not None and (self.optimizer is not None or self.lr_scheduler is not None):
    602     raise RuntimeError(
    603         "Passing a `model_init` is incompatible with providing the `optimizers` argument. "
    604         "You should subclass `Trainer` and override the `create_optimizer_and_scheduler` method."
    605     )

TypeError: cannot unpack non-iterable NoneType object

**Comment by avsolatorio** [comment]
Hello @adgirban, thank you for reporting this! I have published the updated package containing the fix from this PR https://github.com/worldbank/REaLTabFormer/pull/91 . This should be working now. Please try again. :)
